### ISSUE TITLE
Compiling/Playing

### ISSUE THREAD

**Issue by ThePersonhere** [Leather128/LeatherEngineGodot#11]
(holy shit how did I add a issue without a desc)
I don't know how to compile at all to play, so uh yeah.. can someone tell me how to compile? also is LE (in godot) compatible with lua? specifically psych engine lua

**Comment by Leather128** [comment]
1st uh you don't really compile the engine you open the source code as a project in [godot](https://godotengine.org)
2nd no there is 0 lua support in the engine as it would probably be a pain to implement (especially because godot and haxeflixel (which is psych engine's engine of choice) work completely differently and converting code like that would be very difficult)

**Comment by ThePersonhere** [comment]
how the hell do I open a project in godot it opens up it in debug and crashes instantly, otherwise it opens up in a game editing studio
